### ISSUE TITLE
my kafka version is 1.0.0，kafka server got the err:Magic v0 does not support record headers

### ISSUE THREAD

**Issue by wjzsuperman** [childe/healer#8]
kafka get the error like followers: 
Error when handling request {replica_id=-1,max_wait_time=100,min_bytes=1,topics=[{topic=wj.sleuth.test,partitions=[{partition=17,fetch_offset=0,max_bytes=10485760}]}]} (kafka.server.KafkaApis)
java.lang.IllegalArgumentException: Magic v0 does not support record headers
        at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:403)
        at org.apache.kafka.common.record.MemoryRecordsBuilder.append(MemoryRecordsBuilder.java:586)

ghangout got the err:

E0410 14:14:52.967678   53245 fetch_response.go:255] The server experienced an unexpected error when processing the request
I0410 14:14:52.967687   53245 simple_consumer.go:341] consumer wj.sleuth.test[29] error:The server experienced an unexpected error when processing the request
I0410 14:14:52.967722   53245 simple_consumer.go:309] simple consumer stop consuming wj.sleuth.test[29]
E0410 14:14:52.968932   53245 fetch_response.go:255] The server experienced an unexpected error when processing the request

**Comment by wjzsuperman** [comment]
sorry,i write the wrong project
